using BinarySerialization.SourceGenerator.GeneratedTemplates;

namespace BinarySerialization.SourceGenerator.GeneratedAttributes;

public static class BinaryFieldAttributeDeclaration
{
    public static readonly string Text = 
        $$"""
          {{GenerationTemplates.AutoGenerated}}
          {{GenerationTemplates.NullableEnabled}}
          
          {{GenerationAttributesTemplates.NameSpace}};
          
          {{GenerationTemplates.GeneratedCodeAttribute}}
          {{GenerationTemplates.FieldOrPropertyUsageAttribute}}
          {{GenerationTemplates.PublicClass}} FieldAttribute : {{GenerationAttributesTemplates.Attribute}} 
          { 
                public int Position { get; init; }
          }
          """;
    
}