using BinarySerialization.SourceGenerator.GeneratedTemplates;

namespace BinarySerialization.SourceGenerator.GeneratedAttributes;

public static class BinarySerializableAttributeDeclaration
{
    public static readonly string Text = 
        $$"""
          {{GenerationTemplates.AutoGenerated}}
          {{GenerationTemplates.NullableEnabled}}

          {{GenerationAttributesTemplates.NameSpace}};

          {{GenerationTemplates.GeneratedCodeAttribute}}
          {{GenerationTemplates.ClassOrStructUsageAttribute}}
          {{GenerationTemplates.PublicClass}} BinarySerializableAttribute : {{GenerationAttributesTemplates.Attribute}} 
          { }
          """;
}