using BinarySerialization.SourceGenerator.GeneratedTemplates;

namespace BinarySerialization.SourceGenerator.GeneratedAttributes;

public static class BinaryNumFieldAttributeDeclaration
{
    public static readonly string Text = 
        $$"""
          {{GenerationTemplates.AutoGenerated}}
          {{GenerationTemplates.NullableEnabled}}
          
          {{GenerationAttributesTemplates.NameSpace}};
          
          {{GenerationTemplates.GeneratedCodeAttribute}}
          {{GenerationTemplates.FieldOrPropertyUsageAttribute}}
          {{GenerationTemplates.PublicClass}} NumFieldAttribute : {{GenerationAttributesTemplates.Attribute}}
          { 
                public int Position { get; init; }
                public bool IsLittleEndian { get; init; } = true;
          }
          """;
    
}