using BinarySerialization.SourceGenerator.GeneratedTemplates;

namespace BinarySerialization.SourceGenerator.CommonGeneratedTypes;

public class EnumEncodingDeclaration
{
    private const string EnumName = "Encoding";
    private const string Utf8 = nameof(Utf8);
    private const string Utf16 = nameof(Utf16);
    private const string Utf32 =  nameof(Utf32);
    private const string ASCII =  nameof(ASCII);
    private const string Unicode =  nameof(Unicode);
    
    public static readonly string Text = 
        $$"""
          {{GenerationTemplates.AutoGenerated}}
          {{GenerationTemplates.NullableEnabled}}

          {{GenerationCommonTypesTemplates.NameSpace}};

          {{GenerationTemplates.GeneratedCodeAttribute}}
          {{GenerationTemplates.PublicEnum}}  {{EnumName}}
          { 
                {{Utf8}},
                {{Utf16}},
                {{Utf32}},
                {{ASCII}},
                {{Unicode}},
          }
          """;
}