using BinarySerialization.SourceGenerator.GeneratedTemplates;

namespace BinarySerialization.SourceGenerator.CommonGeneratedTypes;

public class EnumEndianDeclaration
{
    private const string EnumName = "Endian";
    private const string LittleEndian = "Little";
    private const string BigEndian = "Big";
    public static readonly string Text = 
        $$"""
          {{GenerationTemplates.AutoGenerated}}
          {{GenerationTemplates.NullableEnabled}}

          {{GenerationCommonTypesTemplates.NameSpace}}

          {{GenerationTemplates.GeneratedCodeAttribute}}
          {{GenerationTemplates.ClassOrStructUsageAttribute}}
          {{GenerationTemplates.PublicEnum}} {{EnumName}}  
          { 
            {{LittleEndian}},
            {{BigEndian}},
          }
          """;
}