using BinarySerialization.SourceGenerator.GeneratedTemplates;

namespace BinarySerialization.SourceGenerator.CommonGeneratedTypes;

public class InterfaceIBinarySerializableDeclaration
{
    private const string InterfaceName = "IBinarySerializable";
    public static readonly string Text = 
        $$"""
          {{GenerationTemplates.AutoGenerated}}
          {{GenerationTemplates.NullableEnabled}}

          {{GenerationCommonTypesTemplates.NameSpace}};

          {{GenerationTemplates.GeneratedCodeAttribute}}
          {{GenerationTemplates.PublicInterface}} {{InterfaceName}}  
          { 
                byte[] ToBytes();
                string AsHexString(char separator = '_'); 
                string TableInfo();
          }
          """;
}