namespace BinarySerialization.SourceGenerator.GeneratedTemplates;

internal static class GenerationTemplates
{
    public static readonly string GeneratedCodeAttribute = 
        $"""[global::System.CodeDom.Compiler.GeneratedCodeAttribute("{typeof(BinarySerializerSourceGenerator).Assembly.GetName().Name}", "{typeof(BinarySerializerSourceGenerator).Assembly.GetName().Version}")]""";

    public const string BaseNamespace = $"namespace {BaseNamespaceName}";
    public const string BaseNamespaceName = "Hepret.BinarySerialization";
    public const string AutoGenerated = "// <auto-generated/>";
    public const string NullableEnabled = "#nullable enable";
    public const string ClassOrStructUsageAttribute = "[global::System.AttributeUsageAttribute(global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct, Inherited = false, AllowMultiple = false)]";
    public const string FieldOrPropertyUsageAttribute = "[global::System.AttributeUsageAttribute(global::System.AttributeTargets.Field | global::System.AttributeTargets.Property, Inherited = false, AllowMultiple = false)]";
    private const string Public = "public";
    public const string PublicClass = $"{Public} class";
    public const string PublicEnum = $"{Public} enum";
}